version: '3'
services:
  mysql:
    build: 'docker/mysql'
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test01
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test_db1