datasource:
  host: localhost
  port: 13306
  database: testdb
  username: testuser
  password: testuser
  jdbc-driver-class: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://${datasource.host}:${datasource.port}/${datasource.database}?characterEncoding=utf8&useSSL=false
  timeZone: Asia/Tokyo
  runtime-configuration-file: reladomo/config/ReladomoRuntimeConfiguration.xml